#!/bin/bash -x

# Exit on errors
set -e

pushd $OPENSHIFT_DEPENDENCIES_DIR
# Get the plantuml jar file from our github repository
wget --no-clobber https://github.com/candlepin/openshift-plantuml-cartridge/raw/master/usr/lib/plantuml.jar
printf '#!/bin/bash\n\njava -jar $OPENSHIFT_DEPENDENCIES_DIR/plantuml.jar $@\n' > plantuml
chmod 700 plantuml
popd

# Create the shell script required to run plantuml and add it to the path
export PATH=$PATH:$OPENSHIFT_DEPENDENCIES_DIR

# Check the plantuml version
plantuml -v

export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8

# rack-jekyll should take care of building the site when it starts and
# it will serve an temporary page informing the user of the outage.  If
# we perform the rendering during the Openshift "build" phase, the application
# serves nothing and the user gets an unpleasant 503 error.  However, if it
# comes to pass that we do need to build during the actual build phase, the
# lines below can be uncommented.

# pushd $OPENSHIFT_REPO_DIR
# bundle exec jekyll build
# popd
