# Do not use tabs in this file!
repository: https://github.com/candlepin/candlepin

# Required for running on Ruby 1.9
encoding: utf-8

# Change this if we ever need the site to reside in a sub-directory
baseurl: ''

include:
  - '.well-known'

exclude:
  - 'vendor'
  # For some reason OpenShift v3 installs to "bundle" instead of "vendor"
  - 'bundle'
  - 'Gemfile*'
  - 'README.md'
  - 'config.ru'
  - 'Dockerfile'
  - 'local_test.sh'

projects_dir: 'docs'

paginate: 8
paginate_path: /news/page:num

sass:
  sass_dir: _sass
  style: :compressed

markdown: KramdownPygments
kramdown:
  # Use GitHub flavor markdown
  input: GFM
  hard_wrap: false

# See http://jekyllrb.com/docs/configuration/#frontmatter-defaults
defaults:
  - scope:
      path: "swagger"
    values:
      layout: "swagger"
  - scope:
      path: "docs"
    values:
      layout: "default"

  - scope:
      path: "news"
    values:
      layout: "news"

  - scope:
      path: "_posts"
    values:
      layout: "news"
      permalink: "/news/:year/:title.html"

  - scope:
      path: "presentations"
    values:
      layout: "presentation"

plugins:
  - jekyll-sitemap
  - jekyll-plantuml
  - jekyll-paginate
