#!/bin/bash

# Exit on errors
set -e

# Get the plantuml jar file from our github repository
wget https://github.com/candlepin/openshift-plantuml-cartridge/raw/master/usr/lib/plantuml.jar

# Create the shell script required to run plantuml and add it to the path
printf '#!/bin/bash\n\njava -jar plantuml.jar $@\n' > plantuml
chmod 700 plantuml
export PATH=$PATH:$TRAVIS_BUILD_DIR

# Check the plantuml version
plantuml -v

export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
bundle exec jekyll build
